### ISSUE TITLE
Beak does not rotate correctly 

### ISSUE THREAD

**Issue by KrisDavie** [aertslab/MendelCraft#1]
Beak rotates with the body, not with the head (at a strange angle): http://imgur.com/a/Q8vxz

Possibly an issue with forge version mismatch?

**Comment by quinten991** [comment]
I cannot reproduce it on my pc but I will take a look at it now that I have this code.

**Comment by KrisDavie** [comment]
Ok thanks. From what I am aware of, we haven't touched any of the code that should affect this, hence why I think it is an issue with the forge version or something similar. 

Just so you are aware, the main thing (and I think only thing) that we have changed is the ability to add a frequency to the presence of an allele when random chickens are spawned.

It could be that it is a server/client issue. I have a feeling that I didn't see the bug when running minecraft from the IDE. We have a server running with this version of the mod
[mendelcraft-9.zip](https://github.com/aertslab/MendelCraft/files/544032/mendelcraft-9.zip), I will e-mail you the details so you can test there if you still cant repro.

**Comment by KrisDavie** [comment]
Fixed by quinten (https://github.com/aertslab/MendelCraft/commit/c7e333898c2520e383ce5188685206edb05d4dd7 and https://github.com/aertslab/MendelCraft/commit/bd041dca88714d5f3840db05bae3c3fa7ec5a8f4)
